spring:
  datasource:
    url: jdbc:mysql://db_chefemcasa:3306/chefeemcasa
    username: root
    password: receita123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
