spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chefemcasa
    username: chef
    password: receita123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  resources:
    static-locations:
      - classpath:/static/
      - file:uploads/recipes/
      - file:uploads/users/
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
